# Site settings
title: labCeroUno laboratorio de bits
email: admin@labcerouno.com
description: Transformamos ceros y unos en aplicaciones

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://labcerouno.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: 
disqus_account: labCeroUno

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/labCeroUno
  - title: facebook
    url: https://facebook.com/labCeroUno
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  - title: github
    url: http://github.com/labcerouno

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, plugins]
# Build settings
